version: '3.1'

services:
  web:
   build:
     context: .
     dockerfile: Dockerfile.dockerfile
   ports:
    - 8443:8443
   depends_on:
    - db
   restart: on-failure

  db:
    image: mysql:oraclelinux8
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-p>    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Rudy2442.
      MYSQL_DATABASE: bdd_candread
      MYSQL_USER: rudy
    ports:
     - 3306:3306
    volumes:
     - ./mysql:/var/lib/mysql